name: cebu_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  charts_flutter: ^0.12.0
  fl_chart: ^0.62.0
  image_picker: ^1.0.8
  pdf: ^3.0.1
  path_provider: ^2.0.2
  intl: ^0.17.0
  flutter_form_builder: ^8.0.0
  printing: ^5.0.1
  material_design_icons_flutter: ^7.0.7296
  http: ^1.2.2
  bcrypt: ^1.1.3


flutter:
  uses-material-design: true
  assets:
    - lib/common/assets/images/
    - lib/common/assets/icons/

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "lib/common/assets/images/logo.png"
    icon_size: 48
